package ru.jira.mapstruct.plugin.demo.resource;

import lombok.RequiredArgsConstructor;
import ru.jira.mapstruct.plugin.demo.dto.SomeRequestDto;
import ru.jira.mapstruct.plugin.demo.dto.SomeResponseDto;
import ru.jira.mapstruct.plugin.demo.mapper.SomeDtoMapper;

import javax.ws.rs.Consumes;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

@Path("/demo-mapper")
@RequiredArgsConstructor
public class DemoMapperResource {
    /*
        This mapper will be generated by MapStruct and injected as Spring Bean
     */
    private final SomeDtoMapper someDtoMapper;

    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    public SomeResponseDto someResponseDto(final SomeRequestDto someRequestDto) {
        return someDtoMapper.toResponseDto(someRequestDto);
    }
}
